use_frameworks!

target 'SGSketchLayer-OC_Example' do
  pod 'SGSketchLayer-OC', :path => '../SGSketchLayer-OC.podspec'

#  target 'SGSketchLayer-OC_Tests' do
#    inherit! :search_paths

#    pod 'FBSnapshotTestCase'
#  end
end
